services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - memory-quasar-network

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - api
    networks:
      - memory-quasar-network

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/dbname?schema=public
    networks:
      - memory-quasar-network

  admin:
    build:
      context: ./apps/admin
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    depends_on:
      - api
    networks:
      - memory-quasar-network

networks:
  memory-quasar-network:
    driver: bridge

volumes:
  postgres_data: 